# The directory containing the source files to parse recursively
source: ../scss

# The directory that aigis will build to
dest: ./www

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./template_ejs
template_engine: ejs

preview_class: 'sg-preview'
timestamp_format: 'DD/MM/YYYY HH:mm'
