# A sample Gemfile
source "https://rubygems.org"

gem "sass", "~> 3.4" # 3.4.X
gem "compass", "~> 1" # 1.X
gem "susy", "~> 2" # 2.X
gem "hologram", "~> 1" # 1.X
gem "psych", "2.0.5"
gem "rouge", "1.9.0"
gem 'wdm', '>= 0.1.0'
gem "guard-hologram"
